[project]
name = 'Planck-Scale-Physics-Explorer'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-analysis]
path = 'contracts/data-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.experimental-setup]
path = 'contracts/experimental-setup.clar'
clarity_version = 2
epoch = 2.5

[contracts.planck-scale-nft]
path = 'contracts/planck-scale-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
